### PR TITLE
Update sigs.yml

### PR DESCRIPTION
**Pull request by joebuss**
Changed meeting date

### CODE REVIEW

**Comment by joebuss** [comment]
This should be pretty basic

**Review by baylessj — APPROVED** [review]
LGTM. Glad to see that you all have set up CI to build the site rather than pushing the built site like I had it set up before.

**Comment by KritR** [comment]
This might actually be an issue because I don't know if yaml likes hyphens ...

**Comment by KritR** [comment]
nevermind works fine !

**Review by KritR — APPROVED** [review]

**Pull request merged**
