### PR TITLE
Update for Fall2020

### PR DESCRIPTION
**Pull request by purdueacm**

### CODE REVIEW

**Review by joebuss — APPROVED** [review]
Should work

**Comment by jpitlor** [comment]
looks like all of the links got changed to absolute file paths. that will definitely break things

**Comment by joebuss** [comment]
I assumed those were just auto-generated, pretty sure I didn't write them in there

**Comment by jpitlor** [comment]
if the site is still using jekyll, the `_site` directory is the autogenerated one, so you'll want to make sure any link outside of that folder is relative to the site root.

**Pull request closed without merging**
