### PR TITLE
⬆ New site layout

### PR DESCRIPTION
**Pull request by baylessj**
🎉 Upgrade to the site's UI! 🎉

The goal with this upgrade is to firstly improve the look of the site, but also hopefully make it a bit easier to modify in the future too.

# Site Mechanics
The site is built with [Jekyll](https://jekyllrb.com/), a static site generator. Building with Jekyll comes with some pros and cons:

- Pros: Allows for users to modify the source with no knowledge of html or the website's layout, the data for the site is all found in `.yml` configuration files in `src/_data/index`. The site's layout adapts to the change in content to look good even with a dramatic change in content.
- Cons: Building requires some dependencies. I added a Makefile for convenience, but the user still has to install ruby and jekyll to use the Makefile. Should we do as per the [pros-docs](https://github.com/purduesigbots/pros-docs) and have users install requirements with pip?

# Todo:
Before these changes get applied, a couple of tasks ought to be accomplished:

- Determine the best way to have the docs built. Could this be a script configured to run any time that the site is pushed, or should we recommend that officers that are updating the docs install Jekyll and its dependencies?
- Approve site layout and proofread content - now is the best chance to re-evaluate our branding and "About Us" section

# Preview of how the site looks currently
websitescreenshot

### CODE REVIEW

**Comment by jpitlor** [comment]
A few concerns:

- I'm sure this is a problem with my machine, but just running the following:

```bash
$ git clone https://github.com/baylessj/acm-website
$ cd acm-website
$ jekyll serve
```

Gives me the following error:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'src/static/css/custom.scss':
    File to import not found or unreadable: search. on line 1
```

- This could have been fixed, but that's an outdated SIGApp logo
- We meet in B160
- We don't do iOS
- I should get you a squircle BoilerFaves logo so we don't have that weird shadow

**Comment by baylessj** [comment]
- I received the same error when building from the `acm-website` directory - the key is to build only from the `acm-website/src` directory. It's a rather odd structure, but the Liquid inclusion in `src/index.html` requires that it be in a different directory than the built `index.html` file. I'll update the README file to make this more clear, that was an oversight on my part.
- Those are holdovers from the old website, I'll update them in a commit after the README one.
- A different Boilerfaves logo would be much appreciated, if you could update it or just send the logo to me in Slack that would be awesome!

**Comment by jpitlor** [comment]
Okay, so regarding the boilerfaves icon, we may need to regenerate the icons because the file we're looking for was probably lost. Just merge for now and i'll get you the icon in the fall when I can talk to everyone

**Comment by oggnik** [comment]
Commenting based on the preview image:
1. It may be helpful to indicate which projects belong to which SIGS.  So like SIGBOTS - PROS, SIGAPP - BoilerFaves, etc..
2. We should update the sponsors to match our current sponsors.  I believe these are only Hawken Media and Microsoft.
3. Files such as 'src/_site/robots.txt' currently reference localhost, not acm.cs.purdue.edu.  This was changed in 551e838 (Add Corec monitor).  Not sure if this was intended...

I like the look so far!

**Review by oggnik — APPROVED** [review]
Looks good to me 👍

**Review by edjubuh — APPROVED** [review]
🎉 Looks good

**Pull request merged**
